import type { CalcInput } from "./types";

export interface Preset {
  id: string;
  name: string;
  icon: string;
  description: string;
  input: Partial<CalcInput>;
}

export const PRESETS: Preset[] = [
  {
    id: "uuni",
    name: "Uuni / liesi",
    icon: "🍳",
    description: "Sähköliesi tai uuni, tyypillisesti 7–10 kW",
    input: {
      powerW: 9000,
      phase: "3-phase",
      cosPhi: 1.0,
      installMethod: "A2",
      cableLengthM: 15,
      loadType: "general",
      protectionType: "MCB-C",
    },
  },
  {
    id: "kiuas-9",
    name: "Kiuas 9 kW",
    icon: "🧖",
    description: "Sähkökiuas 9 kW (esim. Harvia Vega)",
    input: {
      powerW: 9000,
      phase: "3-phase",
      cosPhi: 1.0,
      installMethod: "C",
      cableLengthM: 20,
      loadType: "general",
      protectionType: "MCB-C",
    },
  },
  {
    id: "kiuas-6",
    name: "Kiuas 6 kW",
    icon: "🧖",
    description: "Sähkökiuas 6 kW, 1-vaihe (pieni sauna)",
    input: {
      powerW: 6000,
      phase: "1-phase",
      cosPhi: 1.0,
      installMethod: "C",
      cableLengthM: 15,
      loadType: "general",
      protectionType: "MCB-C",
    },
  },
  {
    id: "kiuas-10.5",
    name: "Kiuas 10.5 kW",
    icon: "🧖",
    description: "Sähkökiuas 10.5 kW (iso sauna/taloyhtiö)",
    input: {
      powerW: 10500,
      phase: "3-phase",
      cosPhi: 1.0,
      installMethod: "C",
      cableLengthM: 25,
      loadType: "general",
      protectionType: "MCB-C",
    },
  },
  {
    id: "ev-11",
    name: "EV 11 kW",
    icon: "🔌",
    description: "Sähköauton lataus 11 kW (3×16A)",
    input: {
      powerW: 11000,
      phase: "3-phase",
      cosPhi: 1.0,
      installMethod: "C",
      cableLengthM: 25,
      loadType: "general",
      protectionType: "MCB-C",
    },
  },
  {
    id: "ev-22",
    name: "EV 22 kW",
    icon: "🔌",
    description: "Sähköauton lataus 22 kW (3×32A)",
    input: {
      powerW: 22000,
      phase: "3-phase",
      cosPhi: 1.0,
      installMethod: "C",
      cableLengthM: 25,
      loadType: "general",
      protectionType: "MCB-C",
    },
  },
  {
    id: "ev-3.7",
    name: "EV 3.7 kW",
    icon: "🔌",
    description: "Sähköauton hidas lataus 3.7 kW (1×16A)",
    input: {
      powerW: 3700,
      phase: "1-phase",
      cosPhi: 1.0,
      installMethod: "C",
      cableLengthM: 20,
      loadType: "general",
      protectionType: "MCB-C",
    },
  },
  {
    id: "pistorasia",
    name: "Pistorasiapiiri",
    icon: "🔲",
    description: "Yleispistorasiat, max 16 A",
    input: {
      powerW: 3680,
      phase: "1-phase",
      cosPhi: 1.0,
      installMethod: "A2",
      cableLengthM: 20,
      loadType: "general",
      protectionType: "MCB-B",
    },
  },
  {
    id: "valaistus",
    name: "Valaistus",
    icon: "💡",
    description: "Valaistuspiiri, 10 A",
    input: {
      powerW: 1500,
      phase: "1-phase",
      cosPhi: 0.95,
      installMethod: "A1",
      cableLengthM: 25,
      loadType: "lighting",
      protectionType: "MCB-B",
    },
  },
  {
    id: "lattialammitys",
    name: "Lattialämmitys",
    icon: "🌡️",
    description: "Sähköinen lattialämmitys, 1–6 kW",
    input: {
      powerW: 3000,
      phase: "1-phase",
      cosPhi: 1.0,
      installMethod: "A1",
      cableLengthM: 15,
      loadType: "general",
      protectionType: "MCB-B",
    },
  },
  {
    id: "lamminvesivaraaja",
    name: "Lämminvesivaraaja",
    icon: "🚿",
    description: "Varaajan vastus, 3–6 kW",
    input: {
      powerW: 3000,
      phase: "1-phase",
      cosPhi: 1.0,
      installMethod: "C",
      cableLengthM: 10,
      loadType: "general",
      protectionType: "MCB-B",
    },
  },
  {
    id: "ilmalampopumppu",
    name: "Ilmalämpöpumppu",
    icon: "❄️",
    description: "ILP ulkoyksikkö, 1–3 kW",
    input: {
      powerW: 2500,
      phase: "1-phase",
      cosPhi: 0.85,
      installMethod: "C",
      cableLengthM: 15,
      loadType: "general",
      protectionType: "MCB-C",
    },
  },
];
